---
title: "Graphics_ggplot2"
author: "SKP"
date: "15 August 2018"
output: html_document
---
#Learning ggplot2

We're learning ggplot2 It's going to be amazing.

###NOTE click "insert >R" at top of editor pane
###from CRAN:
```{r}
#install.packages("tidyverse")
library(tidyverse)

#x <- mpg
#?mpg

#define aesthetics (aes), by selecting the variables to be plotted and the
#variables to define the presentation such as plotting size, shape color, etc.

#add geoms - graphical representation of the data in the plot (points, lines, bars). ggplot2 offers many different geoms; we will use some common ones today, including:

    #geom_point() for scatter plots, dot plots, etc.
    #geom_bar() for bar charts
    #geom_line() for trend lines, time-series, etc


ggplot(data=mpg,aes(x=displ,y=hwy)) +
  geom_point()

#OR

# Assign plot to a variable
car_plot <- ggplot(data = mpg, aes(x = displ, y = hwy))

# Draw the plot
car_plot + 
  geom_point()

#add transparency
ggplot(data = mpg, aes(x = displ, y = hwy)) +
    geom_point(alpha = 0.4)

#map class to colour
ggplot(data = mpg, aes(x = displ, y = hwy)) +
    geom_point(aes(color = class))

#map class to shape
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))

#Make a scatterplot of hwy vs cty with different size points representing each car class and different colors for each fuel type.
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = cty, y = hwy, size = class, color = fl))

```

##text

```{r}

```

##text
